export interface SpeciesInfo {
  id: string;
  live_weight_kg: { min: number; max: number; avg: number };
  carcass_weight_kg: { min: number; max: number };
  carcass_yield_pct: number;
  biltong_yield_kg: { min: number; max: number };
  bone_pct: number;
  meat_pct: number;
  fat_pct: number;
  biltong_conversion: number;
  danger_level: "safe" | "low" | "moderate" | "high" | "dangerous";
  difficulty: "easy" | "moderate" | "hard" | "very hard";
  best_calibers: string[];
  min_caliber: string;
  shot_placement: string;
  best_time: string;
  habitat: string;
  trophy_rw_minimum: string;
  trophy_sci_minimum: string;
  trophy_good: string;
  trophy_exceptional: string;
  world_record: string;
  hunting_method: string;
  rut_season: string;
  nicknames: string[];
  fun_fact: string;
  af_name: string;
}

export const SPECIES_INFO: SpeciesInfo[] = [
  {
    id: "steenbok",
    live_weight_kg: { min: 7, max: 16, avg: 11 },
    carcass_weight_kg: { min: 4, max: 9 },
    carcass_yield_pct: 56,
    biltong_yield_kg: { min: 1, max: 3 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "safe",
    difficulty: "moderate",
    best_calibers: [".243 Win", ".270 Win", ".308 Win"],
    min_caliber: ".222 Rem",
    shot_placement: "Aim one third up from belly directly above front leg. Small target — accuracy critical.",
    best_time: "Early morning and late afternoon. Often solitary.",
    habitat: "Open dry savanna, Karoo, grassland with low shrubs.",
    trophy_rw_minimum: "4 inches",
    trophy_sci_minimum: "19 points",
    trophy_good: "4.5 inches",
    trophy_exceptional: "5.5+ inches",
    world_record: "6 1/4 inches",
    hunting_method: "Walk and stalk. Solitary animal. Freezes when alarmed — use this window.",
    rut_season: "Year-round breeding",
    nicknames: ["Steenbok", "Steinbuck"],
    fun_fact: "Steenbok dig holes to bury their dung — one of very few antelope that do this.",
    af_name: "Steenbok",
  },
  {
    id: "duiker",
    live_weight_kg: { min: 12, max: 25, avg: 18 },
    carcass_weight_kg: { min: 7, max: 14 },
    carcass_yield_pct: 56,
    biltong_yield_kg: { min: 2, max: 5 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "safe",
    difficulty: "hard",
    best_calibers: [".243 Win", ".270 Win"],
    min_caliber: ".222 Rem",
    shot_placement: "High heart/lung shot directly above front leg one third up body.",
    best_time: "Early morning and evening. Secretive and elusive.",
    habitat: "Thick bush, forest edges, dense riverine vegetation.",
    trophy_rw_minimum: "4 inches",
    trophy_sci_minimum: "20 points",
    trophy_good: "4.5 inches",
    trophy_exceptional: "5.5+ inches",
    world_record: "7 3/8 inches",
    hunting_method: "Walk and stalk in dense bush. Difficult to spot. Often uses alarm calls of other species.",
    rut_season: "Year-round breeding",
    nicknames: ["Common Duiker", "Grey Duiker", "Bush Duiker"],
    fun_fact: "The duiker gets its name from the Afrikaans word for 'diver' — it dives into thick bush when alarmed.",
    af_name: "Duiker",
  },
  {
    id: "warthog",
    live_weight_kg: { min: 45, max: 110, avg: 80 },
    carcass_weight_kg: { min: 25, max: 60 },
    carcass_yield_pct: 56,
    biltong_yield_kg: { min: 8, max: 20 },
    bone_pct: 19, meat_pct: 67, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "low",
    difficulty: "easy",
    best_calibers: [".243 Win", ".270 Win", ".308 Win"],
    min_caliber: ".243 Win",
    shot_placement: "High heart/lung shot. Aim directly above front leg one third up body. Brain shot when kneeling at waterhole.",
    best_time: "Morning and evening at waterholes. Diurnal.",
    habitat: "Open savanna, grassland, vleis. Never far from water.",
    trophy_rw_minimum: "12 inches",
    trophy_sci_minimum: "60 points",
    trophy_good: "15 inches",
    trophy_exceptional: "20+ inches",
    world_record: "26 inches",
    hunting_method: "Ambush at waterhole. Walk and stalk on open grassland. Often seen kneeling to graze.",
    rut_season: "May to July",
    nicknames: ["Vlakvark", "Pumba"],
    fun_fact: "Warthogs run with their tails straight up — this helps piglets follow their mother through tall grass.",
    af_name: "Vlakvark",
  },
  {
    id: "mountain-reed",
    live_weight_kg: { min: 19, max: 38, avg: 30 },
    carcass_weight_kg: { min: 11, max: 22 },
    carcass_yield_pct: 56,
    biltong_yield_kg: { min: 3, max: 7 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.34,
    danger_level: "safe",
    difficulty: "hard",
    best_calibers: [".243 Win", ".270 Win"],
    min_caliber: ".243 Win",
    shot_placement: "High heart/lung shot one third up body above front leg.",
    best_time: "Early morning on mountain slopes.",
    habitat: "Rocky mountain terrain, steep slopes, cliff edges.",
    trophy_rw_minimum: "8 inches",
    trophy_sci_minimum: "40 points",
    trophy_good: "9 inches",
    trophy_exceptional: "11+ inches",
    world_record: "14 3/8 inches",
    hunting_method: "Arduous mountain walk and stalk. Physical fitness essential. Glass from ridgelines.",
    rut_season: "June to August",
    nicknames: ["Rooiribbok", "Mountain Reedbuck"],
    fun_fact: "Mountain reedbuck whistle sharply through their nostrils as an alarm call — often heard before the animal is seen.",
    af_name: "Rooiribbok",
  },
  {
    id: "springbok",
    live_weight_kg: { min: 25, max: 48, avg: 37 },
    carcass_weight_kg: { min: 14, max: 28 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 5, max: 10 },
    bone_pct: 16, meat_pct: 70, fat_pct: 14, biltong_conversion: 0.34,
    danger_level: "safe",
    difficulty: "moderate",
    best_calibers: [".243 Win", ".270 Win", ".308 Win"],
    min_caliber: ".243 Win",
    shot_placement: "High heart/lung shot one third up body above front leg. Long shots common on Karoo flats.",
    best_time: "Early morning and late afternoon. Midday in shade.",
    habitat: "Open Karoo, Kalahari scrub, semi-arid grasslands.",
    trophy_rw_minimum: "14 inches",
    trophy_sci_minimum: "68 points",
    trophy_good: "16 inches",
    trophy_exceptional: "18+ inches",
    world_record: "19 7/8 inches",
    hunting_method: "Spot and stalk across open terrain. Long range shots common 200-400m. Glass from vehicle.",
    rut_season: "March to May",
    nicknames: ["Springbok", "Springbuck", "SA national animal"],
    fun_fact: "Springbok can leap 3.5 metres high — the jumping display called 'pronking' may signal fitness to predators.",
    af_name: "Springbok",
  },
  {
    id: "bushbuck",
    live_weight_kg: { min: 24, max: 77, avg: 45 },
    carcass_weight_kg: { min: 14, max: 44 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 5, max: 15 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "moderate",
    difficulty: "hard",
    best_calibers: [".270 Win", ".308 Win", ".30-06"],
    min_caliber: ".243 Win",
    shot_placement: "High heart/lung shot one third up body. Tough for size. Follow up shots often needed.",
    best_time: "Early morning and late afternoon in riverine bush.",
    habitat: "Dense riverine bush, forest edges, kloofs and ravines.",
    trophy_rw_minimum: "16 inches",
    trophy_sci_minimum: "75 points",
    trophy_good: "17 inches",
    trophy_exceptional: "19+ inches",
    world_record: "22 inches",
    hunting_method: "Walk and stalk in dense bush. Extremely secretive. Often stationary for long periods.",
    rut_season: "Year-round breeding",
    nicknames: ["Bosbok", "Harnessed antelope"],
    fun_fact: "Wounded bushbuck ram is considered one of Africa's most dangerous small antelope — will charge and gore hunters.",
    af_name: "Bosbok",
  },
  {
    id: "reedbuck",
    live_weight_kg: { min: 40, max: 90, avg: 65 },
    carcass_weight_kg: { min: 23, max: 52 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 8, max: 18 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "safe",
    difficulty: "moderate",
    best_calibers: [".270 Win", ".308 Win"],
    min_caliber: ".243 Win",
    shot_placement: "High heart/lung shot one third up body above front leg.",
    best_time: "Early morning and evening near water and reedbeds.",
    habitat: "Vleis, marshes, reedbeds, floodplains near rivers.",
    trophy_rw_minimum: "12 inches",
    trophy_sci_minimum: "65 points",
    trophy_good: "14 inches",
    trophy_exceptional: "16+ inches",
    world_record: "18 3/4 inches",
    hunting_method: "Walk and stalk near water. Often flushes from reedbeds with loud whistle alarm call.",
    rut_season: "Year-round breeding",
    nicknames: ["Rietbok", "Common Reedbuck"],
    fun_fact: "The reedbuck's loud whistling alarm bark can be heard over 1km away.",
    af_name: "Rietbok",
  },
  {
    id: "impala",
    live_weight_kg: { min: 40, max: 75, avg: 55 },
    carcass_weight_kg: { min: 23, max: 44 },
    carcass_yield_pct: 58,
    biltong_yield_kg: { min: 8, max: 15 },
    bone_pct: 15, meat_pct: 72, fat_pct: 13, biltong_conversion: 0.34,
    danger_level: "safe",
    difficulty: "easy",
    best_calibers: [".270 Win", ".308 Win", ".30-06"],
    min_caliber: ".243 Win",
    shot_placement: "One third up body directly above front leg. High heart/lung. Be careful not to overshoot into herd.",
    best_time: "Early morning and late afternoon. Rut April-May — rams distracted and visible.",
    habitat: "Open woodland, bushveld, mopane scrub. Always near water.",
    trophy_rw_minimum: "25 5/8 inches (60cm)",
    trophy_sci_minimum: "52 points combined",
    trophy_good: "22 inches",
    trophy_exceptional: "25+ inches",
    world_record: "31 3/8 inches",
    hunting_method: "Walk and stalk. Spot from vehicle. Ambush at waterhole. Most common first African trophy.",
    rut_season: "April to May",
    nicknames: ["Rooibok", "Bread and butter of African hunting"],
    fun_fact: "Impala can leap 10 metres in length and 3 metres in height — often in zigzag patterns to confuse predators.",
    af_name: "Rooibok",
  },
  {
    id: "fallow-deer",
    live_weight_kg: { min: 40, max: 100, avg: 60 },
    carcass_weight_kg: { min: 23, max: 58 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 8, max: 20 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "safe",
    difficulty: "moderate",
    best_calibers: [".270 Win", ".308 Win"],
    min_caliber: ".243 Win",
    shot_placement: "High heart/lung shot one third up body above front leg.",
    best_time: "Early morning and late afternoon. Rut (roar) in autumn.",
    habitat: "Introduced to SA game farms. Open woodland and grassland.",
    trophy_rw_minimum: "Antler span 24 inches",
    trophy_sci_minimum: "170 points",
    trophy_good: "Palmated antlers with good span",
    trophy_exceptional: "Good palmation and 28+ inch span",
    world_record: "N/A in SA context",
    hunting_method: "Walk and stalk. Easy target on game farms. Rut hunting most exciting.",
    rut_season: "April to May in Southern Hemisphere",
    nicknames: ["Damhert", "Fallow"],
    fun_fact: "Fallow deer are not indigenous to SA — all animals are game farm bred descendants of European imports.",
    af_name: "Damhert",
  },
  {
    id: "blesbok",
    live_weight_kg: { min: 55, max: 100, avg: 70 },
    carcass_weight_kg: { min: 32, max: 58 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 11, max: 20 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "safe",
    difficulty: "easy",
    best_calibers: [".270 Win", ".308 Win", ".30-06"],
    min_caliber: ".243 Win",
    shot_placement: "High heart/lung directly above front leg one third up body. Open terrain allows good shot selection.",
    best_time: "Early morning and late afternoon on open highveld.",
    habitat: "Open highveld grassland. Very common on Free State and Mpumalanga farms.",
    trophy_rw_minimum: "16 inches",
    trophy_sci_minimum: "80 points",
    trophy_good: "17 inches",
    trophy_exceptional: "19+ inches",
    world_record: "22 inches",
    hunting_method: "Walk and stalk on open grassland. Often a vehicle-assisted hunt. Medium range shots 100-250m.",
    rut_season: "March to May",
    nicknames: ["Blesbok", "Blessbuck"],
    fun_fact: "Blesbok and bontebok are the same species — bontebok is found only in the Western Cape and has white legs.",
    af_name: "Blesbok",
  },
  {
    id: "nyala",
    live_weight_kg: { min: 55, max: 140, avg: 107 },
    carcass_weight_kg: { min: 32, max: 81 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 11, max: 28 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "low",
    difficulty: "moderate",
    best_calibers: [".270 Win", ".308 Win", ".30-06", "7mm Rem Mag"],
    min_caliber: ".270 Win",
    shot_placement: "High heart/lung one third up body above front leg. Bull has heavy mane — allow for this.",
    best_time: "Early morning and late afternoon. Bushes around water.",
    habitat: "Dense coastal bush, riverine vegetation, KwaZulu-Natal thickets.",
    trophy_rw_minimum: "26 inches",
    trophy_sci_minimum: "115 points",
    trophy_good: "27 inches",
    trophy_exceptional: "30+ inches",
    world_record: "34 1/4 inches",
    hunting_method: "Walk and stalk in dense bush. Ambush at feeding sites and water. Males stay in cover.",
    rut_season: "Year-round breeding",
    nicknames: ["Njala", "KwaZulu antelope"],
    fun_fact: "Male and female nyala look so different they were initially classified as different species.",
    af_name: "Njala",
  },
  {
    id: "black-wilde",
    live_weight_kg: { min: 100, max: 180, avg: 155 },
    carcass_weight_kg: { min: 58, max: 104 },
    carcass_yield_pct: 58,
    biltong_yield_kg: { min: 20, max: 36 },
    bone_pct: 18, meat_pct: 68, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "moderate",
    difficulty: "moderate",
    best_calibers: [".308 Win", ".30-06", "7mm Rem Mag", ".300 Win Mag"],
    min_caliber: ".270 Win",
    shot_placement: "High heart/lung one third up body. Tough animal — premium bullets essential. Follow up quickly.",
    best_time: "Early morning on open highveld.",
    habitat: "Open highveld grassland. Central SA. Drier than blue wildebeest habitat.",
    trophy_rw_minimum: "19 inches spread",
    trophy_sci_minimum: "100 points",
    trophy_good: "21 inches spread",
    trophy_exceptional: "24+ inches spread",
    world_record: "28 5/8 inches",
    hunting_method: "Walk and stalk or vehicle-assisted spot and stalk on open highveld. Medium range shots.",
    rut_season: "February to March",
    nicknames: ["Swart Wildebees", "White-tailed Gnu"],
    fun_fact: "Black wildebeest nearly went extinct in the 1800s — less than 600 remained. Now over 18,000 exist thanks to game farms.",
    af_name: "Swart Wildebees",
  },
  {
    id: "gemsbok",
    live_weight_kg: { min: 150, max: 300, avg: 200 },
    carcass_weight_kg: { min: 87, max: 174 },
    carcass_yield_pct: 58,
    biltong_yield_kg: { min: 30, max: 60 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "moderate",
    difficulty: "moderate",
    best_calibers: [".308 Win", ".30-06", ".300 Win Mag"],
    min_caliber: ".270 Win",
    shot_placement: "High heart/lung one third up body. Long straight horns — do not mistake for cow. Both sexes have horns.",
    best_time: "Early morning in arid areas. Heat tolerant — active longer than other species.",
    habitat: "Kalahari desert, semi-arid scrub, Northern Cape. Heat and drought tolerant.",
    trophy_rw_minimum: "38 inches",
    trophy_sci_minimum: "160 points",
    trophy_good: "40 inches",
    trophy_exceptional: "44+ inches",
    world_record: "47 1/4 inches",
    hunting_method: "Walk and stalk. Long range shots 200-400m common in open Kalahari. Vehicle-assisted.",
    rut_season: "Year-round breeding",
    nicknames: ["Gemsbok", "Oryx", "Kalahari antelope"],
    fun_fact: "Gemsbok can survive body temperatures of 45°C — their nasal passages cool blood before it reaches the brain.",
    af_name: "Gemsbok",
  },
  {
    id: "tsessebe",
    live_weight_kg: { min: 100, max: 180, avg: 140 },
    carcass_weight_kg: { min: 58, max: 104 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 20, max: 36 },
    bone_pct: 18, meat_pct: 68, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "safe",
    difficulty: "moderate",
    best_calibers: [".270 Win", ".308 Win", ".30-06"],
    min_caliber: ".270 Win",
    shot_placement: "High heart/lung one third up body above front leg.",
    best_time: "Early morning on open bushveld.",
    habitat: "Open savanna, lightly wooded grassland. Limpopo and Mpumalanga.",
    trophy_rw_minimum: "14 inches",
    trophy_sci_minimum: "70 points",
    trophy_good: "15 inches",
    trophy_exceptional: "17+ inches",
    world_record: "18 5/8 inches",
    hunting_method: "Walk and stalk or vehicle spot. Often stands on termite mounds as sentinel.",
    rut_season: "January to February",
    nicknames: ["Basterhartbees", "Tsessebe"],
    fun_fact: "The tsessebe is Africa's fastest antelope — can run at 90 km/h over short distances.",
    af_name: "Basterhartbees",
  },
  {
    id: "red-hartebeest",
    live_weight_kg: { min: 100, max: 200, avg: 150 },
    carcass_weight_kg: { min: 58, max: 116 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 20, max: 40 },
    bone_pct: 18, meat_pct: 68, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "safe",
    difficulty: "easy",
    best_calibers: [".270 Win", ".308 Win", ".30-06"],
    min_caliber: ".270 Win",
    shot_placement: "High heart/lung one third up body. Large body makes shot placement straightforward.",
    best_time: "Early morning and late afternoon on open plains.",
    habitat: "Open grassland, light bushveld, semi-arid areas. Very common in Northern Cape.",
    trophy_rw_minimum: "19 inches",
    trophy_sci_minimum: "95 points",
    trophy_good: "22 inches",
    trophy_exceptional: "25+ inches",
    world_record: "28 1/8 inches",
    hunting_method: "Walk and stalk or vehicle. Curious animal — often stands and stares. Easy shot opportunities.",
    rut_season: "January to March",
    nicknames: ["Rooihartbees", "Red Hartebeest"],
    fun_fact: "Hartebeest can survive without water for long periods by eating moisture-rich succulents.",
    af_name: "Rooihartbees",
  },
  {
    id: "waterbuck",
    live_weight_kg: { min: 160, max: 300, avg: 220 },
    carcass_weight_kg: { min: 93, max: 174 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 32, max: 60 },
    bone_pct: 19, meat_pct: 66, fat_pct: 15, biltong_conversion: 0.32,
    danger_level: "low",
    difficulty: "moderate",
    best_calibers: [".30-06", "7mm Rem Mag", ".300 Win Mag"],
    min_caliber: ".270 Win",
    shot_placement: "High heart/lung one third up body. Large body and thick neck — use premium bullets. Tough animal.",
    best_time: "Morning and evening near rivers and water sources.",
    habitat: "Riverine bush, vleis, near permanent water. Never far from rivers.",
    trophy_rw_minimum: "27 inches",
    trophy_sci_minimum: "120 points",
    trophy_good: "28 inches",
    trophy_exceptional: "32+ inches",
    world_record: "38 3/4 inches",
    hunting_method: "Ambush near water or walk and stalk in riverine bush.",
    rut_season: "Year-round breeding",
    nicknames: ["Waterbok", "Waterbuck"],
    fun_fact: "Waterbuck meat has a strong musky smell from sebaceous glands — most hunters do not eat the meat.",
    af_name: "Waterbok",
  },
  {
    id: "zebra",
    live_weight_kg: { min: 220, max: 400, avg: 320 },
    carcass_weight_kg: { min: 127, max: 232 },
    carcass_yield_pct: 58,
    biltong_yield_kg: { min: 45, max: 80 },
    bone_pct: 18, meat_pct: 67, fat_pct: 15, biltong_conversion: 0.33,
    danger_level: "low",
    difficulty: "easy",
    best_calibers: [".308 Win", ".30-06", "7mm Rem Mag", ".300 Win Mag"],
    min_caliber: ".308 Win",
    shot_placement: "High heart/lung one third up body. Stripe pattern can confuse aim point — focus on anatomy not stripes.",
    best_time: "Morning and evening. Grazers active on open plains.",
    habitat: "Open grassland, savanna, bushveld. Widespread across SA.",
    trophy_rw_minimum: "Hide trophy — no horn measurement",
    trophy_sci_minimum: "Hide trophy — skull measured",
    trophy_good: "Good stripe contrast, thick neck, no scars",
    trophy_exceptional: "Full hide mount with perfect striping",
    world_record: "N/A — hide trophy",
    hunting_method: "Walk and stalk or vehicle spot. Herd animal — identify target carefully. Tough body.",
    rut_season: "Year-round breeding",
    nicknames: ["Bontsebra", "Plains Zebra", "Burchell's Zebra"],
    fun_fact: "Each zebra's stripe pattern is unique — like a human fingerprint. No two zebras are alike.",
    af_name: "Bontsebra",
  },
  {
    id: "sable",
    live_weight_kg: { min: 190, max: 270, avg: 220 },
    carcass_weight_kg: { min: 110, max: 157 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 38, max: 55 },
    bone_pct: 18, meat_pct: 68, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "moderate",
    difficulty: "hard",
    best_calibers: [".30-06", "7mm Rem Mag", ".300 Win Mag"],
    min_caliber: ".308 Win",
    shot_placement: "High heart/lung one third up body. Wounded sable is dangerous — will turn and fight. Follow up carefully.",
    best_time: "Early morning. Bulls often solitary or in small bachelor groups.",
    habitat: "Mixed woodland with medium grass. Limpopo, Mpumalanga, Waterberg.",
    trophy_rw_minimum: "39 inches",
    trophy_sci_minimum: "155 points",
    trophy_good: "43 inches",
    trophy_exceptional: "47+ inches",
    world_record: "65 inches",
    hunting_method: "Walk and stalk in woodland. Difficult to approach. Mature bulls separate from herds.",
    rut_season: "April to August",
    nicknames: ["Swartwitpens", "Sable"],
    fun_fact: "Sable antelope are considered by many professional hunters to be the most beautiful antelope in Africa.",
    af_name: "Swartwitpens",
  },
  {
    id: "blue-wilde",
    live_weight_kg: { min: 150, max: 300, avg: 250 },
    carcass_weight_kg: { min: 87, max: 174 },
    carcass_yield_pct: 58,
    biltong_yield_kg: { min: 30, max: 60 },
    bone_pct: 18, meat_pct: 68, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "low",
    difficulty: "easy",
    best_calibers: [".308 Win", ".30-06", "7mm Rem Mag", ".300 Win Mag"],
    min_caliber: ".270 Win",
    shot_placement: "High heart/lung one third up body. Large shoulder hump is NOT the aim point — aim behind the front leg.",
    best_time: "Morning and evening. Herd animals easy to locate.",
    habitat: "Open savanna, bushveld, grassland. Most common large game in SA.",
    trophy_rw_minimum: "27 inches spread",
    trophy_sci_minimum: "120 points",
    trophy_good: "28 inches spread",
    trophy_exceptional: "32+ inches spread",
    world_record: "59 1/4 inches",
    hunting_method: "Vehicle spot and stalk or walk and stalk. Most abundant plains game. Good biltong animal.",
    rut_season: "March to April",
    nicknames: ["Blou Wildebees", "GNU", "Brindled Gnu"],
    fun_fact: "Blue wildebeest snort, grunt and moan constantly — described as sounding like a massive frog chorus.",
    af_name: "Blou Wildebees",
  },
  {
    id: "roan",
    live_weight_kg: { min: 220, max: 320, avg: 270 },
    carcass_weight_kg: { min: 127, max: 186 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 45, max: 65 },
    bone_pct: 18, meat_pct: 68, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "moderate",
    difficulty: "hard",
    best_calibers: [".30-06", ".300 Win Mag", ".338 Win Mag"],
    min_caliber: ".308 Win",
    shot_placement: "High heart/lung one third up body. Very tough animal. Premium bonded bullets essential.",
    best_time: "Early morning near water sources.",
    habitat: "Open woodland with medium to long grass. Less common — specific areas only.",
    trophy_rw_minimum: "27 inches",
    trophy_sci_minimum: "118 points",
    trophy_good: "28 inches",
    trophy_exceptional: "30+ inches",
    world_record: "32 7/8 inches",
    hunting_method: "Walk and stalk in specific woodland habitat. Rarer species — requires dedicated hunt.",
    rut_season: "Year-round breeding",
    nicknames: ["Bastergemsbok", "Roan Antelope"],
    fun_fact: "Roan antelope are one of Africa's rarest large antelope — declining populations on government land but recovering on private reserves.",
    af_name: "Bastergemsbok",
  },
  {
    id: "kudu",
    live_weight_kg: { min: 190, max: 270, avg: 220 },
    carcass_weight_kg: { min: 110, max: 157 },
    carcass_yield_pct: 57,
    biltong_yield_kg: { min: 38, max: 55 },
    bone_pct: 18, meat_pct: 67, fat_pct: 15, biltong_conversion: 0.33,
    danger_level: "safe",
    difficulty: "hard",
    best_calibers: [".270 Win", ".30-06", "7mm Rem Mag", ".300 Win Mag"],
    min_caliber: ".270 Win",
    shot_placement: "Come up the foreleg one third into body. High heart/lung. Aim slightly behind leg for liver shot backup.",
    best_time: "Early morning and late afternoon in thick bushveld.",
    habitat: "Thick bushveld, woodland, hills with good cover. Never far from water.",
    trophy_rw_minimum: "53 7/8 inches (137cm) along spiral",
    trophy_sci_minimum: "121 points combined",
    trophy_good: "50 inches",
    trophy_exceptional: "55+ inches. 60 inch = world class",
    world_record: "73 7/8 inches",
    hunting_method: "Walk and stalk in thick bush. Glass edges of cover from high points. Track to water at midday.",
    rut_season: "April to June",
    nicknames: ["Koedoe", "Grey Ghost of Africa"],
    fun_fact: "A kudu bull lays his horns flat along his back when running through thick bush to avoid getting snagged.",
    af_name: "Koedoe",
  },
  {
    id: "buffalo",
    live_weight_kg: { min: 500, max: 900, avg: 750 },
    carcass_weight_kg: { min: 250, max: 450 },
    carcass_yield_pct: 50,
    biltong_yield_kg: { min: 88, max: 158 },
    bone_pct: 21, meat_pct: 64, fat_pct: 15, biltong_conversion: 0.32,
    danger_level: "dangerous",
    difficulty: "very hard",
    best_calibers: [".375 H&H Mag", ".416 Rigby", ".458 Win Mag", ".458 Lott"],
    min_caliber: ".375 H&H Mag",
    shot_placement: "Broadside: heart/lung behind front leg one third up body. Frontal: base of neck or brain shot. Never quartering away — bullet must reach vitals.",
    best_time: "Morning tracking. Follow fresh tracks from overnight grazing areas.",
    habitat: "Dense bush, riverine thickets, reed beds. Needs water daily.",
    trophy_rw_minimum: "40 inches spread",
    trophy_sci_minimum: "101 points",
    trophy_good: "40 inches spread",
    trophy_exceptional: "45+ inches spread. 50 inch = world class Dagga Boy",
    world_record: "64 1/4 inches spread",
    hunting_method: "Track and stalk on foot. Short range 30-80m typical. PH backup mandatory. Never approach wounded buffalo alone.",
    rut_season: "March to May",
    nicknames: ["Buffel", "Black Death", "Dagga Boy (old solitary bull)"],
    fun_fact: "Cape buffalo kill more hunters in Africa than any other species. A wounded buffalo will circle back and ambush its pursuers.",
    af_name: "Buffel",
  },
  {
    id: "eland",
    live_weight_kg: { min: 400, max: 900, avg: 700 },
    carcass_weight_kg: { min: 232, max: 522 },
    carcass_yield_pct: 58,
    biltong_yield_kg: { min: 82, max: 183 },
    bone_pct: 17, meat_pct: 69, fat_pct: 14, biltong_conversion: 0.33,
    danger_level: "low",
    difficulty: "moderate",
    best_calibers: [".300 Win Mag", ".338 Win Mag", ".375 H&H Mag"],
    min_caliber: ".308 Win",
    shot_placement: "High heart/lung one third up body. Largest antelope — massive body. Premium heavy bullets essential.",
    best_time: "Morning. Large body needs shade — less active midday.",
    habitat: "Open woodland, bushveld, grassland. Adaptable. Widespread across SA.",
    trophy_rw_minimum: "29 inches",
    trophy_sci_minimum: "165 points",
    trophy_good: "30 inches",
    trophy_exceptional: "35+ inches",
    world_record: "44 inches",
    hunting_method: "Walk and stalk. Despite size, eland are surprisingly quiet. Tracks large and easy to follow.",
    rut_season: "Year-round breeding",
    nicknames: ["Eland", "Largest African antelope"],
    fun_fact: "Eland make a distinctive clicking sound when walking — caused by tendons in their knees. Heard before they are seen.",
    af_name: "Eland",
  },
  {
    id: "ostrich",
    live_weight_kg: { min: 90, max: 160, avg: 130 },
    carcass_weight_kg: { min: 45, max: 80 },
    carcass_yield_pct: 55,
    biltong_yield_kg: { min: 16, max: 28 },
    bone_pct: 22, meat_pct: 65, fat_pct: 13, biltong_conversion: 0.35,
    danger_level: "moderate",
    difficulty: "easy",
    best_calibers: [".270 Win", ".308 Win", ".30-06"],
    min_caliber: ".270 Win",
    shot_placement: "Mid-body forward behind the wing joint — high heart/lung. NOT a shoulder shot like antelope.",
    best_time: "Morning on open Karoo and Kalahari plains.",
    habitat: "Open semi-arid Karoo, Kalahari, Namaqualand. Game farms.",
    trophy_rw_minimum: "Hide/feather trophy",
    trophy_sci_minimum: "Hide trophy",
    trophy_good: "Mature cock with good plumage",
    trophy_exceptional: "Old cock with full black plumage and red legs",
    world_record: "N/A — hide trophy",
    hunting_method: "Open approach across flat terrain. Long range shots common 100-300m.",
    rut_season: "July to March",
    nicknames: ["Volstruis", "World's largest bird"],
    fun_fact: "An ostrich kick is powerful enough to kill a lion. Their legs can only kick forward — not sideways.",
    af_name: "Volstruis",
  },
  {
    id: "giraffe",
    live_weight_kg: { min: 800, max: 1400, avg: 1200 },
    carcass_weight_kg: { min: 400, max: 700 },
    carcass_yield_pct: 50,
    biltong_yield_kg: { min: 140, max: 245 },
    bone_pct: 20, meat_pct: 65, fat_pct: 15, biltong_conversion: 0.32,
    danger_level: "moderate",
    difficulty: "moderate",
    best_calibers: [".375 H&H Mag", ".416 Rigby", ".458 Win Mag"],
    min_caliber: ".375 H&H Mag",
    shot_placement: "Heart/lung behind front leg, lower on the body than expected. NOT where you think — aim low on the body. Base of neck for spine shot.",
    best_time: "Morning. Most active early.",
    habitat: "Open woodland with tall trees. Limpopo, Kalahari. Needs tall acacia trees.",
    trophy_rw_minimum: "Skull and skin trophy",
    trophy_sci_minimum: "Skull and skin",
    trophy_good: "Mature bull with hardened ossicones",
    trophy_exceptional: "Very old dark bull",
    world_record: "N/A — skull trophy",
    hunting_method: "Walk and stalk across open terrain. Short range preferred. Giraffe fall hard — ensure safe direction of fall.",
    rut_season: "Year-round breeding",
    nicknames: ["Kameelperd", "World's tallest animal"],
    fun_fact: "A giraffe's heart weighs 12kg and generates twice the blood pressure of a human to pump blood up that long neck.",
    af_name: "Kameelperd",
  },
];

export const getSpeciesInfoById = (id: string) => SPECIES_INFO.find((s) => s.id === id);
